const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let currentUser=null, movies=[], selected=null;
async function api(path,options={}){const r=await fetch('/api/'+path,{credentials:'include',headers:{'content-type':'application/json',...(options.headers||{})},...options});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'Алдаа гарлаа');return d}
function open(id){$(id).classList.add('open');document.body.style.overflow='hidden'}function close(){ $$('.modal.open').forEach(x=>x.classList.remove('open'));document.body.style.overflow=''; const v=$('#video');v.pause();v.removeAttribute('src');v.load() }
$$('[data-close]').forEach(x=>x.onclick=close);
async function boot(){await loadMe();await loadMovies()}
async function loadMe(){const d=await api('me');currentUser=d.user;$('#authBtn').textContent=currentUser?currentUser.name:'Нэвтрэх';$('#adminBtn').classList.toggle('hidden',currentUser?.role!=='admin');$('#accountLine').textContent=currentUser?(d.subscription_expires_at>Date.now()?`Premium идэвхтэй • ${new Date(d.subscription_expires_at).toLocaleDateString('mn-MN')} хүртэл`:`${currentUser.email}`):'Нэвтрээгүй'}
async function loadMovies(){const d=await api('movies');movies=d.movies;renderMovies(movies)}
function renderMovies(list){const g=$('#movieGrid');g.innerHTML='';$('#emptyState').classList.toggle('hidden',list.length>0);for(const m of list){const a=document.createElement('article');a.className='movie';a.innerHTML=`<div class="moviePoster">${m.poster_url?`<img src="${m.poster_url}" alt="">`:`<div class="fallback">MOOD</div>`}<span class="badge">${m.unlocked?'▶ НЭЭЛТТЭЙ':'🔒 3,000₮'}</span><div class="movieText"><b>${escapeHtml(m.title)}</b><span>${escapeHtml(m.genre)} · ${m.duration_minutes} мин · 720p</span></div></div>`;a.onclick=()=>showMovie(m);g.appendChild(a)}}
$('#search').oninput=e=>{const q=e.target.value.toLowerCase().trim();renderMovies(movies.filter(m=>m.title.toLowerCase().includes(q)||m.genre.toLowerCase().includes(q)))};
function showMovie(m){selected=m;$('#detailPoster').src=m.poster_url||'';$('#detailPoster').style.display=m.poster_url?'block':'none';$('#detailGenre').textContent=`${m.genre.toUpperCase()} • ${m.duration_minutes} MIN • 720P`;$('#detailTitle').textContent=m.title;$('#detailDesc').textContent=m.description||'Тайлбар оруулаагүй.';$('#playBtn').classList.toggle('hidden',!m.unlocked);$('#buyMovieBtn').classList.toggle('hidden',m.unlocked);open('#detailModal')}
$('#authBtn').onclick=()=>{if(currentUser){ if(confirm('Гарах уу?')) api('logout',{method:'POST'}).then(()=>location.reload()); } else open('#authModal')};
$$('.tab').forEach(t=>t.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');const reg=t.dataset.tab==='register';$('#nameLabel').classList.toggle('hidden',!reg);$('#nameInput').required=reg;$('#authTitle').textContent=reg?'Бүртгүүлэх':'Нэвтрэх';$('#authSubmit').textContent=reg?'Бүртгэл үүсгэх':'Нэвтрэх'});
$('#authForm').onsubmit=async e=>{e.preventDefault();$('#authError').textContent='';const reg=$('.tab.active').dataset.tab==='register';try{await api(reg?'register':'login',{method:'POST',body:JSON.stringify({name:$('#nameInput').value,email:$('#emailInput').value,password:$('#passInput').value})});close();await boot()}catch(err){$('#authError').textContent=err.message}};
$('#subBtn').onclick=$('#subBtn2').onclick=()=>buy('subscription');$('#buySubBtn').onclick=()=>buy('subscription');$('#buyMovieBtn').onclick=()=>buy('movie');
async function buy(type){if(!currentUser){close();open('#authModal');return}try{const d=await api('purchases',{method:'POST',body:JSON.stringify({type,movie_id:selected?.id})});$('#payTitle').textContent=type==='movie'?'Нэг кино — 3,000₮':'30 хоног — 5,000₮';$('#bankName').textContent=d.payment.bank_name;$('#bankAccount').textContent=d.payment.account_number;$('#bankOwner').textContent=d.payment.account_name;$('#payRef').textContent=d.purchase.reference_code;close();open('#paymentModal')}catch(e){alert(e.message)}}
$('#playBtn').onclick=async()=>{try{const d=await api(`stream-url/${selected.id}`);$('#playerTitle').textContent=selected.title;$('#video').src=d.url;close();open('#playerModal');$('#video').play().catch(()=>{})}catch(e){alert(e.message)}};
$('#adminBtn').onclick=async()=>{open('#adminModal');await loadAdminPurchases()};
$('#movieForm').onsubmit=async e=>{e.preventDefault();const vf=$('#videoFile').files[0], pf=$('#posterFile').files[0];if(!vf)return;try{$('#uploadText').textContent='Video upload link үүсгэж байна...';let poster_key=null;if(pf){const s=await api('admin/upload-url',{method:'POST',body:JSON.stringify({kind:'poster',file_name:pf.name})});await uploadFile(s.url,pf,0,.1);poster_key=s.key}const s=await api('admin/upload-url',{method:'POST',body:JSON.stringify({kind:'video',file_name:vf.name})});await uploadFile(s.url,vf,.1,.9);$('#uploadText').textContent='Киноны мэдээлэл хадгалж байна...';await api('admin/movies',{method:'POST',body:JSON.stringify({title:$('#mTitle').value,genre:$('#mGenre').value,description:$('#mDesc').value,duration_minutes:Number($('#mDuration').value),video_key:s.key,poster_key})});$('#uploadBar').style.width='100%';$('#uploadText').textContent='Амжилттай нэмэгдлээ.';e.target.reset();await loadMovies()}catch(err){$('#uploadText').textContent='Алдаа: '+err.message}};
function uploadFile(url,file,startFrac,endFrac){return new Promise((resolve,reject)=>{const x=new XMLHttpRequest();x.open('PUT',url);x.setRequestHeader('Content-Type',file.type||'application/octet-stream');x.upload.onprogress=e=>{if(e.lengthComputable){const frac=startFrac+(e.loaded/e.total)*(endFrac-startFrac);$('#uploadBar').style.width=(frac*100)+'%';$('#uploadText').textContent=`Upload ${(e.loaded/1024/1024).toFixed(0)} / ${(e.total/1024/1024).toFixed(0)} MB`}};x.onload=()=>x.status>=200&&x.status<300?resolve():reject(new Error('R2 upload '+x.status));x.onerror=()=>reject(new Error('Upload тасарлаа'));x.send(file)})}
async function loadAdminPurchases(){try{const d=await api('admin/purchases');const box=$('#adminPurchases');box.innerHTML=d.purchases.filter(p=>p.status==='pending').map(p=>`<div class="payItem"><div><b>${escapeHtml(p.name)} • ${p.amount.toLocaleString()}₮</b><small>${escapeHtml(p.email)} · ${escapeHtml(p.reference_code)} · ${p.type==='movie'?escapeHtml(p.movie_title||'Кино'):'30 хоног'}</small></div><div class="payBtns"><button class="approve" onclick="approvePay(${p.id})">✓</button><button class="reject" onclick="rejectPay(${p.id})">×</button></div></div>`).join('')||'<p class="muted">Хүлээгдэж буй төлбөр алга.</p>'}catch(e){$('#adminPurchases').innerHTML='<p class="error">'+e.message+'</p>'}}
window.approvePay=async id=>{await api(`admin/purchases/${id}/approve`,{method:'POST'});await loadAdminPurchases()};window.rejectPay=async id=>{await api(`admin/purchases/${id}/reject`,{method:'POST'});await loadAdminPurchases()};
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
boot().catch(e=>console.error(e));
